// ---------------------------------------------------------------------------
// AUDIO
// ---------------------------------------------------------------------------
// The game ships real sound files in audio/ - a ratcheting socket wrench for
// clicks, a till drawer and bell for sales, splintering wood for crates, a
// reactor spin-up for nuclear builds. They are generated by tools/make_sounds.py
// (layered synthesis, not downloads) so everything in the repo is ours.
//
// The WebAudio voices below stay as a fallback: if a file is missing, blocked or
// still downloading, that cue is synthesised instead of going silent.
//
// Files load on the first user gesture, because that is when a browser will let
// an AudioContext exist at all.
//
// The music bed is "Fluffing a Duck" by Kevin MacLeod (incompetech.com),
// licensed under Creative Commons: By Attribution 4.0. It is the one file in
// audio/ we did not make ourselves, and the credit sits in Settings too.

import { state } from './state.js';

// Short percussive cues are .wav (mp3 decoders pad the start by a few
// milliseconds, which you can hear on a click); everything longer is .mp3.
const SAMPLE_FILES = {
  click: 'click.wav', tickUp: 'tickUp.wav', drop: 'drop.wav',
  coin: 'coin.wav', buy: 'buy.wav', error: 'error.wav',
  clickBig: 'clickBig.mp3', sell: 'sell.mp3', crate: 'crate.mp3',
  rare: 'rare.mp3', craft: 'craft.mp3', unlock: 'unlock.mp3',
  nuclear: 'nuclear.mp3', crash: 'crash.mp3', nitro: 'nitro.mp3',
  golden: 'golden.mp3', buff: 'buff.mp3', achieve: 'achieve.mp3',
};

// Per-cue trim, so a click that fires ten times a second sits under a sale.
const GAIN = {
  click: 0.42, tickUp: 0.3, drop: 0.5, coin: 0.6, buy: 0.6, error: 0.5,
  clickBig: 0.6, sell: 0.75, crate: 0.7, rare: 0.7, craft: 0.7, unlock: 0.7,
  nuclear: 0.9, crash: 0.8, nitro: 0.6, golden: 0.8, buff: 0.8, achieve: 0.75,
};

// type: 'tone' | 'sweep' | 'noise' | 'chord'
export const CUES = {
  click:    { type: 'tone',  freq: 520,  to: 660,  dur: 0.05, gain: 0.07, wave: 'square' },
  clickBig: { type: 'sweep', freq: 420,  to: 900,  dur: 0.12, gain: 0.09, wave: 'sawtooth' },
  buy:      { type: 'tone',  freq: 300,  to: 240,  dur: 0.09, gain: 0.08, wave: 'triangle' },
  crate:    { type: 'sweep', freq: 180,  to: 520,  dur: 0.22, gain: 0.10, wave: 'sawtooth' },
  drop:     { type: 'tone',  freq: 720,  to: 720,  dur: 0.05, gain: 0.05, wave: 'sine' },
  rare:     { type: 'chord', notes: [660, 880, 1320], dur: 0.45, gain: 0.08, wave: 'triangle' },
  craft:    { type: 'sweep', freq: 240,  to: 880,  dur: 0.3,  gain: 0.09, wave: 'square' },
  sell:     { type: 'chord', notes: [880, 1174], dur: 0.2, gain: 0.08, wave: 'sine' },
  error:    { type: 'tone',  freq: 150,  to: 110,  dur: 0.14, gain: 0.07, wave: 'sawtooth' },
  unlock:   { type: 'chord', notes: [523, 659, 784, 1047], dur: 0.6, gain: 0.07, wave: 'triangle' },
  nuclear:  { type: 'sweep', freq: 90,   to: 1400, dur: 0.9,  gain: 0.12, wave: 'sawtooth' },
  crash:    { type: 'noise', dur: 0.4, gain: 0.12 },
  nitro:    { type: 'sweep', freq: 400,  to: 1500, dur: 0.25, gain: 0.09, wave: 'square' },
  coin:     { type: 'chord', notes: [988, 1319], dur: 0.12, gain: 0.06, wave: 'square' },
  tickUp:   { type: 'tone',  freq: 1200, to: 1400, dur: 0.03, gain: 0.03, wave: 'sine' },
};

const MUSIC_FILE = 'music.mp3';
const MUSIC_LEVEL = 0.32;  // sits under the effects: a sale should still ring out

let ctx = null;
let volume = 1;
const samples = {};        // name -> AudioBuffer
const samplePaths = {};    // name -> url (loaded lazily)

export function setVolume(v) {
  volume = Math.max(0, Math.min(1, v));
  applyMusicLevel();
}
/** How many real sound files decoded, out of how many we ship. */
export function sampleStatus() {
  return { loaded: Object.keys(samples).length, total: Object.keys(SAMPLE_FILES).length };
}
export function getVolume() { return volume; }

function context() {
  if (!ctx) {
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return null;
    ctx = new AC();
  }
  if (ctx.state === 'suspended') ctx.resume().catch(() => {});
  return ctx;
}

let samplesRequested = false;

/** Browsers need a gesture before audio works; call this from the first click. */
export function unlockAudio() {
  context();
  if (!samplesRequested) {
    samplesRequested = true;
    loadPackagedSamples();
    loadMusic();
  }
}

/** Resolve audio/ relative to this module, so the page can live at any path. */
function sampleUrl(file) {
  return new URL('../../audio/' + file, import.meta.url).href;
}

function loadPackagedSamples() {
  useSamples(Object.fromEntries(
    Object.entries(SAMPLE_FILES).map(([name, file]) => [name, sampleUrl(file)]),
  ));
}

export function useSamples(map) {
  Object.assign(samplePaths, map);
  const ac = context();
  if (!ac) return;
  for (const [name, url] of Object.entries(map)) {
    fetch(url)
      .then((r) => (r.ok ? r.arrayBuffer() : Promise.reject(new Error(r.status))))
      .then((buf) => ac.decodeAudioData(buf))
      .then((decoded) => { samples[name] = decoded; })
      .catch(() => { /* fall back to the synth voice for this cue */ });
  }
}

export function play(name, { rate = 1, gain = 1 } = {}) {
  if (state.settings.muted) return;
  const ac = context();
  if (!ac) return;

  if (samples[name]) {
    const src = ac.createBufferSource();
    const g = ac.createGain();
    src.buffer = samples[name];
    src.playbackRate.value = rate;
    g.gain.value = gain * (GAIN[name] || 0.7) * volume;
    src.connect(g).connect(ac.destination);
    src.start();
    return;
  }

  const cue = CUES[name];
  if (!cue) return;
  const t0 = ac.currentTime;
  const master = ac.createGain();
  master.gain.value = (cue.gain || 0.08) * gain * volume;
  master.connect(ac.destination);

  if (cue.type === 'noise') {
    const len = Math.floor(ac.sampleRate * cue.dur);
    const buffer = ac.createBuffer(1, len, ac.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < len; i += 1) data[i] = (Math.random() * 2 - 1) * (1 - i / len);
    const src = ac.createBufferSource();
    src.buffer = buffer;
    const filter = ac.createBiquadFilter();
    filter.type = 'lowpass';
    filter.frequency.setValueAtTime(1800, t0);
    filter.frequency.exponentialRampToValueAtTime(180, t0 + cue.dur);
    src.connect(filter).connect(master);
    src.start(t0);
    master.gain.exponentialRampToValueAtTime(0.0001, t0 + cue.dur);
    return;
  }

  const notes = cue.type === 'chord' ? cue.notes : [cue.freq];
  notes.forEach((freq, i) => {
    const osc = ac.createOscillator();
    const g = ac.createGain();
    osc.type = cue.wave || 'sine';
    osc.frequency.setValueAtTime(freq * rate, t0);
    if (cue.type !== 'chord' && cue.to) {
      osc.frequency.exponentialRampToValueAtTime(Math.max(20, cue.to * rate), t0 + cue.dur);
    }
    const start = t0 + (cue.type === 'chord' ? i * 0.055 : 0);
    g.gain.setValueAtTime(0.0001, start);
    g.gain.exponentialRampToValueAtTime(1 / notes.length, start + 0.012);
    g.gain.exponentialRampToValueAtTime(0.0001, start + cue.dur);
    osc.connect(g).connect(master);
    osc.start(start);
    osc.stop(start + cue.dur + 0.05);
  });
}

export function setMuted(muted) {
  state.settings.muted = !!muted;
  if (!muted) context();
  applyMusicLevel();
}

// --- music ------------------------------------------------------------------
// Decoded once and looped from an AudioBufferSourceNode rather than an <audio>
// tag: a buffer loop is sample-accurate, so there is no gap at the seam, and it
// shares the context the effects already unlocked.

let musicBuffer = null;
let musicSource = null;
let musicGain = null;
let musicLoading = false;

function musicWanted() {
  return state.settings.music !== false && !state.settings.muted;
}

function loadMusic() {
  const ac = context();
  if (!ac || musicLoading || musicBuffer) return;
  musicLoading = true;
  fetch(sampleUrl(MUSIC_FILE))
    .then((r) => (r.ok ? r.arrayBuffer() : Promise.reject(new Error(r.status))))
    .then((buf) => ac.decodeAudioData(buf))
    .then((decoded) => {
      musicBuffer = decoded;
      applyMusicLevel();
    })
    .catch(() => { /* no music is fine - the game is still a game */ })
    .finally(() => { musicLoading = false; });
}

function startMusicSource(ac) {
  if (musicSource || !musicBuffer) return;
  musicGain = ac.createGain();
  musicGain.gain.value = 0.0001;
  musicGain.connect(ac.destination);
  musicSource = ac.createBufferSource();
  musicSource.buffer = musicBuffer;
  musicSource.loop = true;
  musicSource.connect(musicGain);
  musicSource.start();
}

/** Fade the music to wherever the settings say it should be. */
function applyMusicLevel() {
  const ac = ctx;
  if (!ac || !musicBuffer) return;
  const target = musicWanted() ? MUSIC_LEVEL * volume : 0;
  if (target > 0) startMusicSource(ac);
  if (!musicGain) return;
  const t = ac.currentTime;
  musicGain.gain.cancelScheduledValues(t);
  musicGain.gain.setValueAtTime(Math.max(0.0001, musicGain.gain.value), t);
  musicGain.gain.exponentialRampToValueAtTime(Math.max(0.0001, target), t + (target > 0 ? 0.8 : 0.25));
}

export function musicOn() { return state.settings.music !== false; }

/** For the debug panel: is the track decoded, running, and how loud right now. */
export function musicStatus() {
  return { loaded: !!musicBuffer, playing: !!musicSource, level: musicGain ? musicGain.gain.value : 0 };
}

export function setMusic(on) {
  state.settings.music = !!on;
  if (on) { context(); loadMusic(); }
  applyMusicLevel();
}
